routes:
  /signup/: signup
  /signin/: signin
  /subscribe/: subscribe
  /account/: account
  /membership/: membership
  /newsletter/: page-newsletter
  /paypal/: paypal

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
